[project]
title = "Weather"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
name = "Weather"
logo = "images/logo.png"
favicon = "images/fav.ico"
primaryColor = "#F89613"

[data.my_data]
type = "csv"
path = "data/seattle-weather.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 